[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
option_as_alt = "OnlyLeft"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.95
